/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bibliotheque;

import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Myriam
 */
public class Afficher_Triée_Emprunt extends javax.swing.JFrame {

    /**
     * Creates new form Afficher_Triée_Emprunt
     */
    Employee emp;
    String path;
    public Afficher_Triée_Emprunt() {
        initComponents();
    }
     public Afficher_Triée_Emprunt(Employee emp) {
        initComponents();
        this.emp=emp;
        
    }
    
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel29 = new javax.swing.JPanel();
        jPanel30 = new javax.swing.JPanel();
        jPanel31 = new javax.swing.JPanel();
        jPanel32 = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        quit_btn4 = new javax.swing.JButton();
        jLabel40 = new javax.swing.JLabel();
        afficher_btn2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        afficher_btn3 = new javax.swing.JButton();
        afficher_btn4 = new javax.swing.JButton();
        afficher_btn5 = new javax.swing.JButton();
        jLabel43 = new javax.swing.JLabel();
        deconnecter_btn = new javax.swing.JButton();
        home = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel29.setBackground(new java.awt.Color(130, 0, 60));

        jPanel30.setBackground(new java.awt.Color(255, 245, 245));

        jPanel31.setBackground(new java.awt.Color(102, 0, 51));

        jPanel32.setBackground(new java.awt.Color(255, 245, 245));

        jLabel38.setFont(new java.awt.Font("Trebuchet MS", 3, 24)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(130, 0, 60));
        jLabel38.setText("Afficher tous les Emprunts en ordre croissant");

        quit_btn4.setBackground(new java.awt.Color(130, 0, 60));
        quit_btn4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        quit_btn4.setForeground(new java.awt.Color(255, 255, 255));
        quit_btn4.setText("QUIT");
        quit_btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quit_btn4ActionPerformed(evt);
            }
        });

        jLabel40.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(130, 0, 60));
        jLabel40.setText("ADMIN department");

        afficher_btn2.setBackground(new java.awt.Color(130, 0, 60));
        afficher_btn2.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        afficher_btn2.setForeground(new java.awt.Color(255, 255, 255));
        afficher_btn2.setText("Afficher tous");
        afficher_btn2.setToolTipText("");
        afficher_btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                afficher_btn2ActionPerformed(evt);
            }
        });

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Code", "Date_emprunt", "Date_limite", "Livre", "Client", "Done", "photo_livre", "photo_client"
            }
        ));
        jScrollPane1.setViewportView(table);

        afficher_btn3.setBackground(new java.awt.Color(130, 0, 60));
        afficher_btn3.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        afficher_btn3.setForeground(new java.awt.Color(255, 255, 255));
        afficher_btn3.setText("<html>\nAfficher Emprunt<br> En cours</html>");
        afficher_btn3.setToolTipText("");
        afficher_btn3.setActionCommand("<html>\nAfficher Emprunt<br> \n      En cours</html>");
        afficher_btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                afficher_btn3ActionPerformed(evt);
            }
        });

        afficher_btn4.setBackground(new java.awt.Color(130, 0, 60));
        afficher_btn4.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        afficher_btn4.setForeground(new java.awt.Color(255, 255, 255));
        afficher_btn4.setText("<html>\nAfficher Emprunt<br> Effectuées</html>");
        afficher_btn4.setToolTipText("");
        afficher_btn4.setActionCommand("<html>\nAfficher Emprunt<br> \n      Effectués</html>");
        afficher_btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                afficher_btn4ActionPerformed(evt);
            }
        });

        afficher_btn5.setBackground(new java.awt.Color(130, 0, 60));
        afficher_btn5.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        afficher_btn5.setForeground(new java.awt.Color(255, 255, 255));
        afficher_btn5.setText("<html>\nAfficher Emprunts<br> Depassés</html>");
        afficher_btn5.setToolTipText("");
        afficher_btn5.setActionCommand("<html>\nAfficher Emprunt<br> \n      En cours</html>");
        afficher_btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                afficher_btn5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel32Layout = new javax.swing.GroupLayout(jPanel32);
        jPanel32.setLayout(jPanel32Layout);
        jPanel32Layout.setHorizontalGroup(
            jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel32Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 687, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel32Layout.createSequentialGroup()
                        .addGroup(jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel32Layout.createSequentialGroup()
                                .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel40))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel32Layout.createSequentialGroup()
                                .addComponent(afficher_btn3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addGroup(jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(afficher_btn4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(afficher_btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(37, 37, 37)
                                .addGroup(jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel32Layout.createSequentialGroup()
                                        .addComponent(afficher_btn5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(24, 24, 24))
                                    .addComponent(quit_btn4, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addContainerGap())))
        );
        jPanel32Layout.setVerticalGroup(
            jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel32Layout.createSequentialGroup()
                .addGroup(jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel32Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel40))
                    .addGroup(jPanel32Layout.createSequentialGroup()
                        .addContainerGap(33, Short.MAX_VALUE)
                        .addComponent(jLabel38)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel32Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(quit_btn4))
                    .addGroup(jPanel32Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(afficher_btn2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(afficher_btn3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(afficher_btn4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(afficher_btn5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel31Layout = new javax.swing.GroupLayout(jPanel31);
        jPanel31.setLayout(jPanel31Layout);
        jPanel31Layout.setHorizontalGroup(
            jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel31Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel31Layout.setVerticalGroup(
            jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel31Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel30Layout = new javax.swing.GroupLayout(jPanel30);
        jPanel30.setLayout(jPanel30Layout);
        jPanel30Layout.setHorizontalGroup(
            jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel30Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel30Layout.setVerticalGroup(
            jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel30Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bibliotheque/Capture d'écran 2024-03-04 230632.png"))); // NOI18N
        jLabel43.setText("jLabel4");

        deconnecter_btn.setBackground(new java.awt.Color(130, 0, 60));
        deconnecter_btn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        deconnecter_btn.setForeground(new java.awt.Color(255, 255, 255));
        deconnecter_btn.setText("Deconnecter");
        deconnecter_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deconnecter_btnActionPerformed(evt);
            }
        });

        home.setBackground(new java.awt.Color(130, 0, 60));
        home.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        home.setForeground(new java.awt.Color(255, 255, 255));
        home.setText("Home");
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText(" Bibliothèque interuniversitaire ");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Cujas");

        javax.swing.GroupLayout jPanel29Layout = new javax.swing.GroupLayout(jPanel29);
        jPanel29.setLayout(jPanel29Layout);
        jPanel29Layout.setHorizontalGroup(
            jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel29Layout.createSequentialGroup()
                .addGroup(jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel29Layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(jLabel3))
                    .addGroup(jPanel29Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel29Layout.createSequentialGroup()
                                .addComponent(deconnecter_btn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 146, Short.MAX_VALUE)
                                .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))))
                .addGap(18, 18, 18)
                .addComponent(jPanel30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel29Layout.setVerticalGroup(
            jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel29Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deconnecter_btn))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void quit_btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quit_btn4ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_quit_btn4ActionPerformed

    private void afficher_btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_afficher_btn2ActionPerformed
        // TODO add your handling code here:

        DefaultTableModel tableModel = new DefaultTableModel(new Object[][]{}, new Object[]{"Code","Date_emprunt","Date_limite","Client","Livre","Done"});
        Gestion_Employee gest = new Gestion_Employee();
        Vector<Emprunt> list;
        try {
            list = gest.afficher_emprunt_tous();
            for (Emprunt element : list) {

                Object[] rowData = {element.getCode(),element.getDate_emprunt(),element.getDate_limite(),element.getClient().getCin(),element.getLivre().getCode(),element.isDone()};
                tableModel.addRow(rowData);
            }
            table.setModel(tableModel);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Une erreur s'est produite : " + ex.getMessage());
        }
    }//GEN-LAST:event_afficher_btn2ActionPerformed

    private void deconnecter_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deconnecter_btnActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Welcome().setVisible(true);
    }//GEN-LAST:event_deconnecter_btnActionPerformed

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        // TODO add your handling code here:  this.dispose();
        this.dispose();
        new Administration_home(emp).setVisible(true);
    }//GEN-LAST:event_homeActionPerformed

    private void afficher_btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_afficher_btn3ActionPerformed
        // TODO add your handling code here:
          DefaultTableModel tableModel = new DefaultTableModel(new Object[][]{}, new Object[]{"Code","Date_emprunt","Date_limite","Client","Livre","Done"});
        Gestion_Employee gest = new Gestion_Employee();
        Vector<Emprunt> list;
        try {
            list = gest.afficher_tous_emprunt_en_cours();
            for (Emprunt element : list) {

                Object[] rowData = {element.getCode(),element.getDate_emprunt(),element.getDate_limite(),element.getClient().getCin(),element.getLivre().getCode(),element.isDone()};
                tableModel.addRow(rowData);
            }
            table.setModel(tableModel);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Une erreur s'est produite : " + ex.getMessage());
        }
    }//GEN-LAST:event_afficher_btn3ActionPerformed

    private void afficher_btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_afficher_btn4ActionPerformed
        // TODO add your handling code here:
          DefaultTableModel tableModel = new DefaultTableModel(new Object[][]{}, new Object[]{"Code","Date_emprunt","Date_limite","Client","Livre","Done"});
        Gestion_Employee gest = new Gestion_Employee();
        Vector<Emprunt> list;
        try {
            list = gest.afficher_tous_emprunt_effectuee();
            for (Emprunt element : list) {

                Object[] rowData = {element.getCode(),element.getDate_emprunt(),element.getDate_limite(),element.getClient().getCin(),element.getLivre().getCode(),element.isDone()};
                tableModel.addRow(rowData);
            }
            table.setModel(tableModel);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Une erreur s'est produite : " + ex.getMessage());
        }
    }//GEN-LAST:event_afficher_btn4ActionPerformed

    private void afficher_btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_afficher_btn5ActionPerformed
        // TODO add your handling code here:
         DefaultTableModel tableModel = new DefaultTableModel(new Object[][]{}, new Object[]{"Code","Date_emprunt","Date_limite","Client","Livre","Done"});
        Gestion_Employee gest = new Gestion_Employee();
        Vector<Emprunt> list;
        try {
            list = gest.afficher_tous_emprunt_depassee();
            for (Emprunt element : list) {

                Object[] rowData = {element.getCode(),element.getDate_emprunt(),element.getDate_limite(),element.getClient().getCin(),element.getLivre().getCode(),element.isDone()};
                tableModel.addRow(rowData);
            }
            table.setModel(tableModel);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Une erreur s'est produite : " + ex.getMessage());
        }
    }//GEN-LAST:event_afficher_btn5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Afficher_Triée_Emprunt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Afficher_Triée_Emprunt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Afficher_Triée_Emprunt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Afficher_Triée_Emprunt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Afficher_Triée_Emprunt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton afficher_btn2;
    private javax.swing.JButton afficher_btn3;
    private javax.swing.JButton afficher_btn4;
    private javax.swing.JButton afficher_btn5;
    private javax.swing.JButton deconnecter_btn;
    private javax.swing.JButton home;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton quit_btn4;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
