/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bibliotheque;

import javax.swing.JOptionPane;

/**
 *
 * @author Myriam
 */
public class Formulaire extends javax.swing.JFrame {

    /**
     * Creates new form forulaire
     */
    public Formulaire() {
        initComponents();
    }
    
    Client client;
    public Formulaire(Client client) {
        initComponents();
        this.client=client;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        quit_btn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        zero_to_one = new javax.swing.JRadioButton();
        two_to_three = new javax.swing.JRadioButton();
        more_than_five = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        yes = new javax.swing.JRadioButton();
        no = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jamais = new javax.swing.JRadioButton();
        temp = new javax.swing.JRadioButton();
        tjrs = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jamais2 = new javax.swing.JRadioButton();
        bien = new javax.swing.JRadioButton();
        excellent = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        pas_sat = new javax.swing.JRadioButton();
        neutre = new javax.swing.JRadioButton();
        sat = new javax.swing.JRadioButton();
        done = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        quit_btn1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(130, 0, 60));

        jPanel2.setBackground(new java.awt.Color(255, 245, 245));

        jPanel3.setBackground(new java.awt.Color(102, 0, 51));

        jPanel4.setBackground(new java.awt.Color(255, 245, 245));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(130, 0, 60));
        jLabel1.setText("Formulaire_client");

        quit_btn.setBackground(new java.awt.Color(130, 0, 60));
        quit_btn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        quit_btn.setForeground(new java.awt.Color(255, 255, 255));
        quit_btn.setText("QUIT");
        quit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quit_btnActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 51));
        jLabel2.setText("==>Depuis combien de temps utilisez-vous nos services?");

        buttonGroup1.add(zero_to_one);
        zero_to_one.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        zero_to_one.setText("0-1 ans");
        zero_to_one.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zero_to_oneActionPerformed(evt);
            }
        });

        buttonGroup1.add(two_to_three);
        two_to_three.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        two_to_three.setText("2-3 ans");
        two_to_three.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                two_to_threeActionPerformed(evt);
            }
        });

        buttonGroup1.add(more_than_five);
        more_than_five.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        more_than_five.setText("plus de 5 ans");
        more_than_five.setActionCommand("2-3 ans");
        more_than_five.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                more_than_fiveActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 51));
        jLabel3.setText("==>Pensez-vous que nos services se sont améliorés au fil du temps?");

        yes.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        yes.setText("Oui");
        yes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yesActionPerformed(evt);
            }
        });

        no.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        no.setText("Non");
        no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 51));
        jLabel5.setText("==>Dans quelle mesure nos services répondent-ils à vos attentes?");

        jamais.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jamais.setText("Jamais");
        jamais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jamaisActionPerformed(evt);
            }
        });

        temp.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        temp.setText("Environ la moitié du temp");
        temp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tempActionPerformed(evt);
            }
        });

        tjrs.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tjrs.setText("Toujours");
        tjrs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tjrsActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 51));
        jLabel6.setText("==>Comment évaluez-vous la qualité de nos produits / services?");

        jamais2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jamais2.setText("Jamais");
        jamais2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jamais2ActionPerformed(evt);
            }
        });

        bien.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bien.setText("Bien");
        bien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bienActionPerformed(evt);
            }
        });

        excellent.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        excellent.setText("Excellent");
        excellent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excellentActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 51));
        jLabel7.setText("==>Quelle a été votre expérience avec notre service client? ");

        pas_sat.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        pas_sat.setText("Pas Satisfait");
        pas_sat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pas_satActionPerformed(evt);
            }
        });

        neutre.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        neutre.setText("Neutre");
        neutre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                neutreActionPerformed(evt);
            }
        });

        sat.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        sat.setText("Satisfait");
        sat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                satActionPerformed(evt);
            }
        });

        done.setBackground(new java.awt.Color(130, 0, 60));
        done.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        done.setForeground(new java.awt.Color(255, 255, 255));
        done.setText("Done");
        done.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(quit_btn))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(zero_to_one, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(two_to_three, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(more_than_five, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(107, 107, 107)
                                .addComponent(yes, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addComponent(no, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jamais, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(temp)
                                .addGap(18, 18, 18)
                                .addComponent(tjrs, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(jamais2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bien, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(excellent, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(jLabel1))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(pas_sat, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(neutre, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(sat, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(done, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 41, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(zero_to_one)
                    .addComponent(two_to_three)
                    .addComponent(more_than_five))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yes)
                    .addComponent(no))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addGap(15, 15, 15)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jamais)
                    .addComponent(temp)
                    .addComponent(tjrs))
                .addGap(9, 9, 9)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jamais2)
                    .addComponent(bien)
                    .addComponent(excellent))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pas_sat)
                    .addComponent(neutre)
                    .addComponent(sat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quit_btn)
                    .addComponent(done))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bibliotheque/Capture d'écran 2024-03-04 230632.png"))); // NOI18N
        jLabel4.setText("jLabel4");

        quit_btn1.setBackground(new java.awt.Color(130, 0, 60));
        quit_btn1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        quit_btn1.setForeground(new java.awt.Color(255, 255, 255));
        quit_btn1.setText("Return");
        quit_btn1.setContentAreaFilled(false);
        quit_btn1.setEnabled(false);
        quit_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quit_btn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(157, Short.MAX_VALUE)
                        .addComponent(quit_btn1)
                        .addGap(151, 151, 151))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addComponent(quit_btn1)
                .addGap(8, 8, 8))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void quit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quit_btnActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_quit_btnActionPerformed

    private void quit_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quit_btn1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Home().setVisible(true);
    }//GEN-LAST:event_quit_btn1ActionPerformed

    private void yesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yesActionPerformed

    private void noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noActionPerformed

    private void jamaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jamaisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jamaisActionPerformed

    private void tempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tempActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tempActionPerformed

    private void tjrsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tjrsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tjrsActionPerformed

    private void jamais2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jamais2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jamais2ActionPerformed

    private void bienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bienActionPerformed

    private void excellentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excellentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_excellentActionPerformed

    private void pas_satActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pas_satActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pas_satActionPerformed

    private void neutreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_neutreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_neutreActionPerformed

    private void satActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_satActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_satActionPerformed

    private void doneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneActionPerformed
        // TODO add your handling code here:
        String quest1="0";
        String quest2="0";
        String quest3="0";
        String quest4="0";
        String quest5="0";
        try{
        if(zero_to_one.isSelected()){quest1="0-1 ans";}
        else if(two_to_three.isSelected()){quest1="2-3 ans";}
        else if(more_than_five.isSelected()){quest1="more than 3 ans";}
        else{    JOptionPane.showMessageDialog(null,"you have to select the first question"); }
        
        if(yes.isSelected()){quest2="oui";}
        else if(no.isSelected()){quest2="no";}
        else{    JOptionPane.showMessageDialog(null,"you have to select the second question"); }
        
        if(jamais.isSelected()){quest3="jamais";}
        else if(temp.isSelected()){quest3="Environ la moitié du temp";}
        else if(tjrs.isSelected()){quest3="Toujours";}
        else{    JOptionPane.showMessageDialog(null,"you have to select the third question"); }
        
        if(jamais2.isSelected()){quest4="jamais";}
        else if(bien.isSelected()){quest4="Bien";}
        else if(excellent.isSelected()){quest4="Excellent";}
        else{    JOptionPane.showMessageDialog(null,"you have to select the fourth question"); }
        
        if(pas_sat.isSelected()){quest5="pas satisfait";}
        else if(neutre.isSelected()){quest5="neutre";}
        else if(sat.isSelected()){quest5="Satisfait";}
        else{    JOptionPane.showMessageDialog(null,"you have to select the fourth question"); }
       
        Formulaire_client form=new Formulaire_client(client.getCin(),quest1,quest2,quest3,quest4,quest5);
        Gestion_Employee gest=new Gestion_Employee();
        gest.formulaire(form);
           JOptionPane.showMessageDialog(null,"thank youuu you for sharing");
        this.dispose();
          new Client_Home(client).setVisible(true);
       }catch(Exception e){
       JOptionPane.showMessageDialog(null,e);
       }
            

        
    }//GEN-LAST:event_doneActionPerformed

    private void more_than_fiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_more_than_fiveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_more_than_fiveActionPerformed

    private void two_to_threeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_two_to_threeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_two_to_threeActionPerformed

    private void zero_to_oneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zero_to_oneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_zero_to_oneActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulaire().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton bien;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton done;
    private javax.swing.JRadioButton excellent;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jamais;
    private javax.swing.JRadioButton jamais2;
    private javax.swing.JRadioButton more_than_five;
    private javax.swing.JRadioButton neutre;
    private javax.swing.JRadioButton no;
    private javax.swing.JRadioButton pas_sat;
    private javax.swing.JButton quit_btn;
    private javax.swing.JButton quit_btn1;
    private javax.swing.JRadioButton sat;
    private javax.swing.JRadioButton temp;
    private javax.swing.JRadioButton tjrs;
    private javax.swing.JRadioButton two_to_three;
    private javax.swing.JRadioButton yes;
    private javax.swing.JRadioButton zero_to_one;
    // End of variables declaration//GEN-END:variables
}
